<?php

namespace RPGMS\DiceBundle\Repository;

/**
 * RNGRollsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RNGRollsRepository extends \Doctrine\ORM\EntityRepository
{
}
