<?php

namespace RPGMS\DiceBundle\Repository;

/**
 * RollsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RollsRepository extends \Doctrine\ORM\EntityRepository
{
}
