<?php

namespace RpgmsBundle\Repository;

/**
 * DiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiceRepository extends \Doctrine\ORM\EntityRepository
{
}
