<?php

namespace RpgmsBundle\Repository;

/**
 * RollSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RollSetRepository extends \Doctrine\ORM\EntityRepository
{
}
