<?php

namespace RpgmsBundle\Repository;

/**
 * SystemAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
